common: &default_settings
  source: verboice-ui
  debug: false

development:
  <<: *default_settings
  enabled: true
  server: localhost:2120

test:
  <<: *default_settings
  enabled: false

production:
  <<: *default_settings
  enabled: false
